// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"delivery-service/config"
	"delivery-service/internal/adapter/userserv"
	"delivery-service/internal/api"
	"delivery-service/internal/domain/repos"
	"delivery-service/internal/grpc-service/interceptor"
	"delivery-service/internal/grpc-service/protobuf/deliveryGrpc"
	"delivery-service/internal/middleware"
	"delivery-service/internal/publisher"
	"delivery-service/internal/router"
	"delivery-service/internal/service/deliveryserv"
	"delivery-service/internal/service/packageserv"
	"delivery-service/internal/service/shippingserv"
	"delivery-service/internal/subscribers"
	"delivery-service/pkgs/healthservice"
	"delivery-service/pkgs/mongodb"
	"delivery-service/pkgs/rabbitclient"
	"delivery-service/pkgs/resty"
	"encoding/json"
	"github.com/ansrivas/fiberprometheus/v2"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/adaptor"
	"github.com/gofiber/fiber/v2/middleware/basicauth"
	"github.com/gofiber/fiber/v2/middleware/healthcheck"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"github.com/gofiber/fiber/v2/middleware/monitor"
	recover2 "github.com/gofiber/fiber/v2/middleware/recover"
	"github.com/gofiber/swagger"
	"github.com/hellofresh/health-go/v5"
	"google.golang.org/grpc"
	"time"
)

// Injectors from server.go:

func New() (*Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	client := restyclient.InitRestyGoClient(configConfig)
	userService := userserv.NewUserService(client, configConfig)
	mongoClient, err := mongodb.OpenMongoDBConnection(configConfig)
	if err != nil {
		return nil, err
	}
	deliveryRepos := repos.NewDeliveryRepos(mongoClient)
	deliveryService := deliveryserv.NewDeliveryService(userService, deliveryRepos)
	deliveryHandle := api.NewDeliveryHandle(deliveryService)
	provinceRepository := repos.InitProvinceRepository(configConfig)
	shippingCostService := shippingserv.NewShippingCostService(provinceRepository, userService, deliveryRepos)
	shippingHandle := api.NewShippingHandle(shippingCostService)
	districtRepos := repos.InitDistrictRepository(configConfig)
	wardRepos := repos.InitWardRepository(configConfig)
	vietNamProvinceHandle := api.NewVietNamProvinceHandle(provinceRepository, districtRepos, wardRepos)
	authMiddleware := middleware.NewAuthMiddleware(userService)
	routerHandler := router.NewRouterHandler(deliveryHandle, shippingHandle, vietNamProvinceHandle, authMiddleware)
	deliveryServiceServer := deliveryGrpc.NewDeliveryServerGRPC(shippingCostService)
	connection := rabbitclient.NewRabbitClientConnection(configConfig)
	shippingPackageRepos := repos.NewShippingPackageRepos(mongoClient)
	replyPurchasePublisher := publisher.NewReplyPurchasePublisher(configConfig, connection)
	shippingPackageService := packageserv.NewShippingPackageService(deliveryRepos, shippingPackageRepos, replyPurchasePublisher)
	purchaseCreatedSub := subscribers.NewPurchaseCreatedSub(configConfig, connection, shippingPackageService)
	grpcInterceptor := interceptor.NewGrpcInterceptor(configConfig)
	server := NewServer(configConfig, routerHandler, deliveryServiceServer, purchaseCreatedSub, grpcInterceptor)
	return server, nil
}

// server.go:

type Server struct {
	globalCfg   *config.Config
	app         *fiber.App
	grpcServ    *grpc.Server
	purchaseSub *subscribers.PurchaseCreatedSub
}

func NewServer(
	cfg *config.Config, router2 *router.RouterHandler,
	deliServ deliveryGrpc.DeliveryServiceServer,
	purchaseSub *subscribers.PurchaseCreatedSub,
	grpcInterceptor *interceptor.GrpcInterceptor) *Server {

	app := fiber.New(fiber.Config{
		ReadTimeout:  5 * time.Second,
		WriteTimeout: 5 * time.Second,
		JSONDecoder:  json.Unmarshal,
		JSONEncoder:  json.Marshal,
	})

	app.Use(logger.New())

	recoverConfig := recover2.ConfigDefault
	app.Use(recover2.New(recoverConfig))

	app.Get("", func(ctx *fiber.Ctx) error {
		s := struct {
			Message string `json:"message"`
			Version string `json:"version"`
		}{
			Message: "delivery service was developed by TienDat",
			Version: "v1.0.1",
		}
		return ctx.JSON(s)
	})

	basicAuthConfig := basicauth.Config{
		Users: map[string]string{
			cfg.Metrics.Username: cfg.Metrics.Password,
		},
	}

	app.Get("/swagger/*", basicauth.New(basicAuthConfig), swagger.HandlerDefault)

	prometheus := fiberprometheus.New("latipe-delivery-service")
	prometheus.RegisterAt(app, cfg.Metrics.MetricsURL, basicauth.New(basicAuthConfig))
	app.Use(prometheus.Middleware)

	h, _ := healthService.NewHealthCheckService(cfg)
	app.Get("/health", basicauth.New(basicAuthConfig), adaptor.HTTPHandlerFunc(h.HandlerFunc))
	app.Use(healthcheck.New(healthcheck.Config{
		LivenessProbe: func(c *fiber.Ctx) bool {
			return true
		},
		LivenessEndpoint: "/liveness",
		ReadinessProbe: func(c *fiber.Ctx) bool {
			result := h.Measure(c.Context())
			return result.Status == health.StatusOK
		},
		ReadinessEndpoint: "/readiness",
	}))

	app.Get(cfg.Metrics.FiberDashboard, basicauth.New(basicAuthConfig), monitor.New(monitor.Config{Title: "Delivery Services Metrics Page (Fiber)"}))
	api2 := app.Group("/api")
	v1 := api2.Group("/v1")
	router2.
		InitRouter(&v1)

	grpcServ := grpc.NewServer(grpc.UnaryInterceptor(grpcInterceptor.MiddlewareUnaryRequest))
	deliveryGrpc.RegisterDeliveryServiceServer(grpcServ, deliServ)
	return &Server{
		globalCfg:   cfg,
		app:         app,
		purchaseSub: purchaseSub,
		grpcServ:    grpcServ,
	}
}

func (serv Server) PurchaseCreatedSub() *subscribers.PurchaseCreatedSub {
	return serv.purchaseSub
}

func (serv Server) App() *fiber.App {
	return serv.app
}

func (serv Server) Config() *config.Config {
	return serv.globalCfg
}

func (serv Server) DeliServ() *grpc.Server {
	return serv.grpcServ
}
